### ISSUE TITLE
user-can-view-all-groups-and-teams

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

This feature enables user to view all the groups and teams participating in the 2022 World Cup.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive layout that shows all the teams and their corresponding flag along with the groups within the tournament.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue1-desktop](https://user-images.githubusercontent.com/104106959/191077624-d248796d-58e8-4f1d-8bef-9d9806b3343a.png)
## ✅ Task Lists
<img width="725" alt="Screen Shot 2022-09-22 at 2 45 25 PM" src="https://user-images.githubusercontent.com/104106959/191826972-c9a5a8af-16b1-49ee-80e3-521b984f4ccf.png">

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update schema.sql to create data tables for database
- [x] Update data.sql to present values to database that can be manipulated in testing
- [x] Update server/index.js to get and post values to/from the database
    - [x]  Set up preliminaries such as db, app, and middlewares
- [x]  Test with HTTPie
- [x]  Handle all errors and respond to the client
- [x] Enter team info into database

### ☁️ Server Tasks

- [x] install express server

### ⚡ Client Tasks

- [x] create mobile menu with nav links
- [x] create footer menu with icon links
- [x] create mobile second nav for groups
- [x] add all teams to render with corresponding team name and flag and group

### 🧑‍⚕️ Clean Up Tasks

- [x] verify layout is displaying correctly on mobile
- [x]  verify layout is displaying correctly on desktop
- [x] Make sure that no React state objects are being mutated.
- [x]  Remove all console logs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
