### ISSUE TITLE
user-can-view-bracket-with-their-team-selections

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/final-project#10]
6## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their saved bracket populated with their team selections from group stage and can continue their prediction though knockout stages.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

teams get popular from group selections, user can click on any team to select them as the winner progressing through the next round, once a team is selected that team will be populated to the next round field. User can continue until they reach the final round or save their current prediction.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue10-mobile](https://user-images.githubusercontent.com/104106959/191108751-8ca9609b-f491-45f1-937e-0dcf933e3cb9.png)
![issue-10-desktop](https://user-images.githubusercontent.com/104106959/205404880-33c8410b-0f98-42d9-8d10-bc2bbf1730fe.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] verify DB is update with bracket selections
 - [x] verify no duplicates 'brackets' appear on home screen for user
 - [x] verify both group round and knockout round selections load once user clicks on corresponding bracket

### ☁️ Server Tasks

- [x] create fetch request to save bracket picks to DB

### ⚡ Client Tasks

- [x] load team name and flag from group selections
- [x] verify team selection is 'checked' even after user leaves page/section
- [x] verify each knockout round acts independently

### 🧑‍⚕️ Clean Up Tasks

- [x] verify layout is displaying correctly on mobile
- [x]  verify layout is displaying correctly on desktop
- [x]  Remove all console logs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
