### ISSUE TITLE
user-can-automate-group-selection

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can skip and automate group selection to continue directly to the bracket selection, where teams will be selected on behalf of user and populated onto the bracket. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when a user is viewing a blank bracket, if they click on the 'shuffle' icon button, they are prompted to confirm. If user confirms a new bracket is created and group selections are randomized and the bracket is populated.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue-11-mobile](https://user-images.githubusercontent.com/104106959/206576226-734c39a0-8c87-4b36-9d3f-1f35fd8e3f49.png)
![issue-11-desktop](https://user-images.githubusercontent.com/104106959/206576932-83c7b402-6d20-4b61-98ae-0fb770f527ce.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] verify user is prompter before automation begins
- [x] verify user doesn't leave bracket page
- [x] verify the correct teamID are automated within each group
- [x] verify the bracket populates with selected teams 

### 🧑‍⚕️ Clean Up Tasks

- [x] verify layout is displaying correctly on mobile
- [x]  verify layout is displaying correctly on desktop
- [x]  Remove all console logs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
