### ISSUE TITLE
user-can-rename-saved-brackets

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/final-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can rename their saved brackets.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user is viewing their saved brackets, when user clicks on the 'pencil' icon, a text input field will appear where the name was displayed prompting the user to change the name, a checkmark will appear where the pencil was to save the new name.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue13-desktop](https://user-images.githubusercontent.com/104106959/191124971-36e3ccee-ffe2-47f5-9fa7-6be54999893b.png)
![issue13-mobile](https://user-images.githubusercontent.com/104106959/191124973-c12c7476-bc18-42bd-9deb-8adf531669a1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] verify bracket name is changed on DB

### ☁️ Server Tasks

- [x]  create patch request to change bracket name

### ⚡ Client Tasks

- [x] add input to bracket list
- [x] verify input updates in real time with state
- [x] verify named is update on client side after saved icon is clicked

### 🧑‍⚕️ Clean Up Tasks

- [x] verify layout is displaying correctly on mobile
- [x]  verify layout is displaying correctly on desktop
- [x]  Remove all console logs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
