### ISSUE TITLE
user-can-view-each-individual-group

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view each group in the tournament, along with each team participating within that group.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

There is a second navigation showing the different groups, user can select a group they wish to see the teams of,
once a group link is clicked, the page re-renders and shows the corresponding teams from that group. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue2-mobile](https://user-images.githubusercontent.com/104106959/191079941-42a7fbc8-3968-45f9-9cd7-bc7a15b8ae6c.png)
![issue2-desktop](https://user-images.githubusercontent.com/104106959/191079942-6741deb8-cec2-4f62-85c6-c2c37f1d48ab.png)
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] render the groups and its teams on each individual page
- [x] connect hash routing so the correct group appears with the indicated link. 

### 🧑‍⚕️ Clean Up Tasks

- [x] verify layout is displaying correctly on mobile
- [x] verify layout is displaying correctly on desktop
- [x] Make sure that no React state objects are being mutated.
- [x] Remove all console logs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
