### ISSUE TITLE
user-can-view-information-about-any-team

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select any team and view relevant information about any team to make a better prediction of their chances of progressing through the tournament.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User clicks on any team in the group view or all teams view, and a modal appears that shows information and stats about the specific team selected.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-24 at 12 34 05 PM](https://user-images.githubusercontent.com/104106959/192109004-dfc1b92e-38e1-453f-83ed-78e61b59d6cb.png)
![Screen Shot 2022-09-24 at 12 26 30 PM](https://user-images.githubusercontent.com/104106959/192108650-3eb1bf58-d806-4746-8f08-c7a347f60ad2.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] route group title from teams page (any click on the group title should redirect to clicked group)
- [x] create an accordion to hold team information
- [x] click on any team link should trigger the accordion 
- [x] populate the accordion with the team that was clicked info using teamID
- [x] verify you can open two accordions or more at one time

### 🧑‍⚕️ Clean Up Tasks

- [x] verify layout is displaying correctly on mobile
- [x] verify layout is displaying correctly on desktop
- [x] Make sure that no React state objects are being mutated.
- [x] Remove all console logs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
