### ISSUE TITLE
user-can-create-a-new-bracket-prediction

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create new prediction bracket that allows them to select which teams they predict will progress in the tournament.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user clicks on 'start a new prediction' button on the group view or the '+' button on the bracket view, a new prediction is started and will be indicated by the red floating bar above the footer which tells the user which bracket they are working on.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue4-mobile](https://user-images.githubusercontent.com/104106959/191085050-baf10283-6cc8-4b4f-9a76-003492970ea7.png)
![issue4-desktop](https://user-images.githubusercontent.com/104106959/191085051-dd9de6d3-3e15-4106-8751-23eb8ad68bf4.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] ... 
- [x] ...

### ☁️ Server Tasks

- [x] ... 
- [x] ...

### ⚡ Client Tasks

- [x] create pop-up indicating user is editing a bracket
- [x] verify user can click on team and accordion does not show up
- [x] verify user can click on team and change background to indicate selection
- [x] verify once user changes group view and returns to original group, previous selections are still indicated through background color change
- [ ] 

### 🧑‍⚕️ Clean Up Tasks

- [x] verify layout is displaying correctly on mobile
- [x] verify layout is displaying correctly on desktop
- [x] Make sure that no React state objects are being mutated.
- [x] Remove all console logs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
