### ISSUE TITLE
user-can-save-their-prediction

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save the current prediction they are working on.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user is working on a prediction a red bar will appear with the name of the prediction they are working on, if user clicks on the check icon, the current prediction will be saved and user will not be able to make any further predictions. A confirmation pop-up will confirm the action was completed.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue4-mobile](https://user-images.githubusercontent.com/104106959/191093143-b2297da6-b897-4b91-8865-0edba4c4b801.png)
![issue5-mobile](https://user-images.githubusercontent.com/104106959/191093144-cf2bef69-b59c-4011-9914-69562c240798.png)

![issue5-desktop](https://user-images.githubusercontent.com/104106959/191093234-279c312a-582d-46c4-891e-4a0e5362ca53.png)
![issue4-desktop](https://user-images.githubusercontent.com/104106959/191093235-ffa2bbd5-41a7-410f-a015-006b637751d5.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] ... 
- [x] save new user credentials to database
  - [x] verify password is hashed in DB
- [x] verify user can log in
  - [x] verify user has token to remain logged in

### ☁️ Server Tasks

- [x] add post request for new user registration
- [x] add post request for new bracket creation
- [ ] 
### ⚡ Client Tasks

- [x] create login page
- [x] allow user to register
- [x] verify when user starts a new bracket it has a unique ID
- [x] verify when user saves bracket the user ID is saved along with it

### 🧑‍⚕️ Clean Up Tasks

- [x] verify layout is displaying correctly on mobile
- [x]  verify layout is displaying correctly on desktop
- [x] Make sure that no React state objects are being mutated.
- [x]  Remove all console logs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
