### ISSUE TITLE
user-can-edit-a-prediction

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view and edit previous created brackets and continue to work on that specific prediction.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on 'edit previous prediction' button and it will show their previous saved predictions.  After seeing the list of saved predictions, user can click on any saved prediction and continue to work on it after the click the 'pencil' edit icon.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue6-desktop](https://user-images.githubusercontent.com/104106959/191095942-e94e5e66-6fea-46cd-8844-afd3e670cf87.png)
![issue6-mobile](https://user-images.githubusercontent.com/104106959/191095944-3da331cc-fd11-45d3-8790-4fafe336eed0.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] verify patch requests are update in DB

### ☁️ Server Tasks

- [x] create 'fetch' get request to retrieve the bracket selected by user
  - [x] verify the group-stage sets that correspond to the bracketId are also returned.
- [x] create 'fetch' patch request to return the edited content to the DB

### ⚡ Client Tasks

- [x] render all the brackets a user has created on the 'home' page
  - [x] render brackets should be from latest to first created. 
- [x] verify user can click on the name of any bracket that they have created
  - [x] it should redirect them to the group stage
  - [x] it should populate the previous selections
- [x] 'edit prev prediction' button should redirect user to 'home' page

### 🧑‍⚕️ Clean Up Tasks

- [x] verify layout is displaying correctly on mobile
- [x]  verify layout is displaying correctly on desktop
- [x] Make sure that no React state objects are being mutated.
- [x]  Remove all console logs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
