### ISSUE TITLE
user-can-delete-a-prediction

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a saved prediction.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on 'minus' delete icon button, a prompt will appear to confirm if user wants to delete selected bracket, if 'delete' button is click, then bracket is delete and page is rendered showing updated list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue7-mobile](https://user-images.githubusercontent.com/104106959/191099295-5e913df2-00df-4f04-b5a6-e00614f8c9e0.png)
![issue7-desktop](https://user-images.githubusercontent.com/104106959/191099298-881e868e-5ec1-4850-85a2-5fa20e249913.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] verify bracket is deleted
- [x] verify groupStage selections associated with bracketId is deleted

### ☁️ Server Tasks

- [x] create fetch delete request for bracket
- [x] create fetch delete request for groupStage selections

### ⚡ Client Tasks

- [x] assign action to delete icon button
- [x] create prompt to confirm delete
- [x] verify bracket list updates and removes deleted bracket

### 🧑‍⚕️ Clean Up Tasks

- [x] verify layout is displaying correctly on mobile
- [x]  verify layout is displaying correctly on desktop
- [x] Make sure that no React state objects are being mutated.
- [x]  Remove all console logs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
