### ISSUE TITLE
user-can-select-two-teams-to-progress-out-of-group

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select which two teams will progress their respective group, but cannot choose more than two teams. If user tries to select a third team, error message will pop up.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user starts a new prediction, user will be able to click on whichever team they want to select to progress, once a team is click the team will be highlighted to indicated selection. If a user tries to select more than two teams an error message will pop up. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue8-mobile](https://user-images.githubusercontent.com/104106959/191100079-4ea60208-d5b7-43a1-a7e4-5ce5f2c99bb2.png)
![issue8-desktop](https://user-images.githubusercontent.com/104106959/191100080-2cf68b33-97e1-48e8-acd7-21cdb367e971.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] verify user can only select two teams
- [x] verify user can only select teams from group 'A' to a1 & a2, not from any other group
- [x] verify when new bracket is started, it begins at group 'A'

### 🧑‍⚕️ Clean Up Tasks

- [x] verify layout is displaying correctly on mobile
- [x]  verify layout is displaying correctly on desktop
- [x] Make sure that no React state objects are being mutated.
- [x]  Remove all console logs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
