### ISSUE TITLE
user-can-view-a-blank-bracket

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a blank bracket to see the format and how chosen teams can progress through the tournament.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
on mobile, a second nav appears to view different stages of the bracket, user can click through to view different rounds. 
user can also view from 'east/west' views

on desktop, user can view full bracket on screen, and see the different rounds and how teams progress in the tournament.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![issue9-mobile](https://user-images.githubusercontent.com/104106959/191106625-b838e7d7-a1bc-462d-ba46-871d843deb3c.png)
<img width="1038" alt="issue-9-desktop" src="https://user-images.githubusercontent.com/104106959/200677700-a7d83e92-b4ce-4cfb-b2a0-f5fc20245df3.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] create bracket style cards for round of 16
- [x] verify you can see east/west views
- [x] create bracket style cards for QF
- [x] create bracket style cards for SF
- [x] create bracket style cards for Final

### 🧑‍⚕️ Clean Up Tasks

- [x] verify layout is displaying correctly on mobile
- [x]  verify layout is displaying correctly on desktop
- [x] Make sure that no React state objects are being mutated.
- [x]  Remove all console logs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
